edlm/urls.py
from django.urls import path 

from . import views 

urlpatterns = [ 
	path('', views.homePageView.as_view(), name ='home'),
	path('home', views.homePageView.as_view(), name ='hem2'),
	path('sellers', views.sellersPageView.as_view(), name ='sellers'),
	path('buyers', views.buyersPageView.as_view(), name ='buyers'),
	path('brokers', views.brokersPageView.as_view(), name ='brokers'),
	path('assets', views.assetsPageView.as_view(), name ='assets'),
	#path('signup', views.signupPageView.as_view(), name ='signup'),

	path(r'details/<str:ID>', views.detailedPageView.as_view(), name ='details'),
	#path(r'showdetails', views.showdetails, name ='showdetails'),
	path('reports', views.reportsPageView.as_view(), name ='reports'),
	path('maps', views.mapsPageView.as_view(), name ='maps'),
	path('listings', views.listingsPageView.as_view(), name ='listings'),
	path('forsale', views.mapsPageView.as_view(), name ='forsale'),
	path('bidform', views.bidformPageView.as_view(), name ='bidform'),
	path('bidaccept', views.bidacceptPageView.as_view(), name ='bidaccept'),
	path('bidstatus', views.bidstatusPageView.as_view(), name ='bidstatus'),
	path('confirmsale', views.confirmsalePageView.as_view(), name ='confirmsale'),
	path('api/getRoyaltyOwners', views.get_Royalty_Owners, name ='getRoyaltyOwners'),
	path('api/getProductionPayments', views.get_Production_payments, name ='getProductionPayments'),
	path('linechart', views.LineChartJSONView.as_view(), name ='linechart'),
	path('customer/new/', views.customer_new, name='customer_new'),
	path('royalties/new/', views.royalties_new, name='royalties_new'),
	path('bid/new/', views.bid_new, name='bid_new'),
	path('dblistings/new/', views.dblistings_new, name='dblistings_new'),
	path(r'dblistings/edit/', views.dblistings_edit, name='dblistings_edit'),
	path(r'dblistings/edit/(?P<pk>\d+)/', views.dblistings_edit, name='dblistings_edit'),
	path(r'dblistings/new/(?P<pk>\d+)/', views.dblistings_new, name='dblistings_new'),
	path('getMWdata/', views.getMWdata, name='getMWdata'),
	path('setMWdata/', views.setMWdata, name='setMWdata'),
	path(r'royalties/edit/(?P<pk>\d+)/', views.royalties_edit, name='royalties_edit'),
	path(r'royalties/delete/(?P<pk>\d+)/', views.RoyaltiesDelete.as_view(), name='royalties_delete'),
	#path(r'royalties/delete/(?P<pk>\d+)/$', views.royalties_delete, name='royalties_delete'),

]

edomain/urls.py
from django.contrib import admin
from django.urls import path, include
import users.urls

# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('users/', include('users.urls')),
#     path('accounts/', include('django.contrib.auth.urls')),
#     path('', include('edlm.urls')),
# ]




urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('django.contrib.auth.urls')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
    path('', include('edlm.urls')),
]

edlm/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Assetinformation(models.Model):
    asset_id = models.AutoField(db_column='ASSET_ID', primary_key=True)  # Field name made lowercase.
    atype = models.IntegerField(db_column='ATYPE')  # Field name made lowercase.
    asset_no = models.IntegerField(blank=True, null=True)
    beg_date = models.DateField()
    end_date = models.DateField(blank=True, null=True)
    well_id = models.IntegerField(blank=True, null=True)
    tract_id = models.IntegerField(blank=True, null=True)
    mineral_id = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'assetinformation'


class Assetname(models.Model):
    asset_name_id = models.AutoField(db_column='Asset_name_id', primary_key=True)  # Field name made lowercase.
    name = models.CharField(db_column='NAME', max_length=50)  # Field name made lowercase.
    asset_no = models.IntegerField(db_column='ASSET_NO')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'assetname'


class Assettype(models.Model):
    asset_type_id = models.AutoField(primary_key=True)
    asset_type = models.IntegerField()
    asset_name = models.CharField(max_length=64, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'assettype'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class Bid(models.Model):
    bid_id = models.AutoField(db_column='BID_ID', primary_key=True)  # Field name made lowercase.
    oid = models.ForeignKey('Ownership', models.DO_NOTHING, db_column='oid')
    sdate = models.DateTimeField()
    sexpire = models.DateTimeField()
    svalue = models.FloatField(blank=True, null=True)
    state = models.IntegerField()
    bidder = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'bid'


class Customer(models.Model):
    cust_id = models.AutoField(db_column='CUST_ID', primary_key=True)  # Field name made lowercase.
    cust_fname = models.CharField(db_column='CUST_FNAME', max_length=50)  # Field name made lowercase.
    cust_lname = models.CharField(db_column='CUST_LNAME', max_length=50)  # Field name made lowercase.
    cust_no = models.CharField(db_column='CUST_NO', max_length=50)  # Field name made lowercase.
    sign_date = models.DateField(db_column='SIGN_DATE', blank=True, null=True)  # Field name made lowercase.
    image = models.TextField(db_column='IMAGE', blank=True, null=True)  # Field name made lowercase.
    email = models.CharField(db_column='EMAIL', max_length=50, blank=True, null=True)  # Field name made lowercase.
    credit = models.FloatField(db_column='CREDIT', blank=True, null=True)  # Field name made lowercase.
    phone = models.CharField(db_column='PHONE', max_length=50, blank=True, null=True)  # Field name made lowercase.
    cust_address1 = models.CharField(db_column='CUST_ADDRESS1', max_length=50, blank=True, null=True)  # Field name made lowercase.
    cust_address2 = models.CharField(db_column='CUST_ADDRESS2', max_length=50, blank=True, null=True)  # Field name made lowercase.
    cust_city = models.CharField(db_column='CUST_CITY', max_length=50, blank=True, null=True)  # Field name made lowercase.
    cust_zipcode = models.CharField(db_column='CUST_ZIPCODE', max_length=10, blank=True, null=True)  # Field name made lowercase.
    cust_state = models.CharField(db_column='CUST_STATE', max_length=2, blank=True, null=True)  # Field name made lowercase.
    user_name = models.CharField(max_length=32, blank=True, null=True)
    title = models.CharField(db_column='Title', max_length=16, blank=True, null=True)  # Field name made lowercase.
    mobile = models.CharField(db_column='Mobile', max_length=32, blank=True, null=True)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'customer'


class Dblistings(models.Model):
    sale_id = models.AutoField(db_column='SALE_ID', primary_key=True)  # Field name made lowercase.
    oid = models.ForeignKey('Ownership', models.DO_NOTHING, db_column='oid')
    ondate = models.DateField()
    sexpire = models.DateField()
    askvalue = models.FloatField(blank=True, null=True)
    state = models.IntegerField()
    bidid = models.IntegerField(blank=True, null=True)
    soldvalue = models.FloatField(blank=True, null=True)
    solddate = models.DateField(blank=True, null=True)
    soldto = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'dblistings'


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Leasestable(models.Model):
    id = models.IntegerField(primary_key=True)
    tract_id = models.CharField(db_column='Tract ID', max_length=4, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    lease = models.CharField(db_column='Lease', max_length=3, blank=True, null=True)  # Field name made lowercase.
    tract_name = models.CharField(db_column='Tract Name', max_length=4, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    partial = models.CharField(db_column='Partial', max_length=1, blank=True, null=True)  # Field name made lowercase.
    gross_acres = models.IntegerField(db_column='Gross Acres', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    net_acres = models.IntegerField(db_column='Net Acres', blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    legal_description = models.CharField(db_column='Legal Description', max_length=106, blank=True, null=True)  # Field name made lowercase. Field renamed to remove unsuitable characters.
    county = models.CharField(db_column='County', max_length=9, blank=True, null=True)  # Field name made lowercase.
    state = models.CharField(db_column='State', max_length=9, blank=True, null=True)  # Field name made lowercase.
    township = models.CharField(db_column='Township', max_length=10, blank=True, null=True)  # Field name made lowercase.
    lrange = models.CharField(db_column='LRange', max_length=10, blank=True, null=True)  # Field name made lowercase.
    section = models.CharField(db_column='Section', max_length=10, blank=True, null=True)  # Field name made lowercase.

templates/bidStatus.html
{% extends 'base.html' %}

{% block content %}
Bid Status ....
{% endblock %}
{% block currentListings %}
<div class="row">
    <div class="col-lg-4"></div>
    <div class="col-lg-4">
       Report 1 ....
       <ul class="li"></ul>
       <ul class="li"></ul>
       <ul class="li"></ul>
       <ul class="li"></ul>
       <ul class="li"></ul>
    </div>
    <div class="col-lg-4"></div>
</div>
{% endblock %}

templates/buyers.html
{% extends 'base.html' %}
{% csrf_token %}
{% block content %}

{% if user.is_authenticated %}
 


<div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
        <h3>Buyers.  </h3>
        <p>
        
        <p>
        This is a landing page explaining what it means to sell on our platform 
    </div>
    <div class="col-lg-2"></div>
</div>


{% endif %}
                

{% endblock %}

templates/customer_edit.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}
<section class="bg-light">
    <div class="container ed_card">
        <div class="row">
            <div class="col-lg-2"></div>
            <div class="col-lg-8">
                <br>
                <form method="POST" class="customer-form">{% csrf_token %}
                      <h2> Edit profile ..{{ form.pk }}.. </h2>
                      <br>
                         <p>
                        <input id="id_user" type="text" disabled="True" value="{{ user.username}}">
                    </p>
                    {{ form.as_p }}
                    <button type="submit" class="btn-primary">Save</button>
                    {{ saved }}

                </form>
            </div>
        </div>
    </div>
</section>
{% endif %}
{% endblock %}

templates/deleteConfirmation.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-lg-2"></div>
    <div class="col-lg-8">
      <form method="post">{% csrf_token %}
          <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" value="Confirm" />
      </form>
    </div>
    <div class="col-lg-2"></div>
</div>
{% endblock %}

templates/details.html
{% extends 'base.html' %}
{% block extrahead %}
<script src="//cdnjs.cloudflare.com/ajax/libs/Chart.js/0.2.0/Chart.min.js" type="text/javascript"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript">
$( document ).ready(function() {
    var data = {
        labels: {{ labels }},
        datasets: [
            {
                label: "oil revenue",
                fillColor: "rgba(220,220,220,0.2)",
                strokeColor: "rgba(220,220,220,1)",
                pointColor: "rgba(220,220,220,1)",
                pointStrokeColor: "#fff",
                pointHighlightFill: "#fff",
                pointHighlightStroke: "rgba(220,220,220,1)",
                data: {{ oil_revenue }}
            }, 

            {
                label: "gas revenue",
                fillColor: "rgba(100,220,100,0.2)",
                strokeColor: "rgba(10,220,10,1)",
                pointColor: "rgba(220,220,220,1)",
                pointStrokeColor: "#fff",
                pointHighlightFill: "#fff",
                pointHighlightStroke: "rgba(220,220,220,1)",
                data: {{ gas_revenue }}
            }, 



        ]
    };
    var ctx = document.getElementById("myChart").getContext("2d");
    var myLineChart = new Chart(ctx).Line(data);
});
</script>
{% endblock %}
{% block content %}


        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                </div>
                <div class="col-lg-8">
                    my arguments are here ... for {{ ID }}
                </div>
                <div class="col-lg-2">
                </div>
            </div>
        </div>


        <div class="container">
            <div class="row">
                <div class="col-lg-2">
                </div>
                <div class="col-lg-8">
                    <canvas id="myChart" width="800" height="300"></canvas>
                </div>
                <div class="col-lg-2">
                </div>
            </div>
        </div>



{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block content %}
{% if user.is_authenticated %}


<!-- <section class="bg-light">
        <div class="container">
			<div class="row">	
				<div class="col-lg-6">
				<div class="btn-toolbar">
				    <div class="btn-group" role="group">
				    	<button class="btn btn-primary" type="button">Mineral Ware</button>
				    	<button class="btn btn-primary" type="button">Energy Link</button></div>
  			    	<div class="btn-group" role="group"><button class="btn btn-primary" type="button">Button 1</button>
				    		<button class="btn btn-primary" type="button">Button 2</button></div>  
				</div>
				</div>
			</div>
		</div>
	</section> -->


<section class="bg-light">
        <div class="container">
			<div class="row">	
				<div class="col-lg-6">
					<div class="accordion" id="collapsibleTabs">
					  <div class="card">
					    <div class="card-header" id="headingOne">
					      <h5 class="mb-0">
					        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
					          Current Holdings
					        </button>
					      </h5>
					    </div>

					    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#collapsibleTabs">
					      <div class="card-body">
					        <table class="table table-striped table-bordered" border="1"> 


											{% for own in owned  %}
											<div class="card">
												<h5 class="card-title">
													Asset ID: {{own.AID}}
												</h5>
												<h6 class="card-subtitle">Identifier .. {{own.WELL}}</h6>

								            	<p>Asset Type: {{own.Atype}}</p>

								            	<a href="{% url 'dblistings_new' own.AID  %}" class="btn btn-primary">More...</a>

								            </div>

											{% endfor %}
										</table>
					      </div>
					    </div>
  					</div>
  					  <div class="card">
					    <div class="card-header" id="headingOne">
					      <h5 class="mb-0">
					        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
					          Recorded Payments
					        </button>
					      </h5>
					    </div>

					    <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#collapsibleTabs">
					      <div class="card-body">
					        <table class="table table-striped table-bordered" border="1"> 
								        	<tr>
								        		<th>Date</th>
								        		<th>Amount</th>
								        		<th>Number</th>
								        		<th><a href="{% url 'royalties_new'  %}"><i class="fa fa-plus"> </a></i>
												</th>
								            </tr>	
											{% for payment in payments  %}
								            <tr><td>{{payment.check_date}}</td>
								            	<td>{{payment.check_amount}}</td>
								            	<td>{{payment.check_number}}</td>
								            	<td><!-- <a class="nav-link" href="{% url 'royalties_edit' pk=payment.rid  %}"> {{payment.rid}} </a> -->
												<a href="{% url 'royalties_edit' pk=payment.rid  %}"><i class="fa fa-edit"> </a></i>
												<a href="{% url 'royalties_new'  %}"><i class="fa fa-plus"> </a></i>
												<a href="{% url 'royalties_delete' payment.rid  %}"><i class="fa fa-trash"> </a></i>
												
								            	</td>
								            </tr>
											{% endfor %}
										</table>
					      </div>
					    </div>
  					</div>
					  <div class="card">
					    <div class="card-header" id="headingTwo">
					      <h5 class="mb-0">
					        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
					         My Listings
					        </button>
					      </h5>
					    </div>
					    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#collapsibleTabs">
					      <div class="card-body">
							<table class="table table-striped table-bordered" border="1"> 
			        	<tr>
			        		<th>IDr</th>
			        		<th>Who?</th>
			        		<th>Amount</th>
			            </tr>	
						{% for bid in listings  %}
			            <tr><td>{{bid.id}}</td>
			            	<td>{{bid.where}}</td>
			            	<td>{{bid.Amount}}</td>
			            </tr>
						{% endfor %}
					</table>
					      </div>
					    </div>
					  </div>
				  <div class="card">
				    <div class="card-header" id="headingThree">
				      <h5 class="mb-0">
				        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
				          Bids Received
				        </button>
				      </h5>
				    </div>
				    <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#collapsibleTabs">
				      <div class="card-body">
						<table class="table table-striped table-bordered" border="1"> 
			        	<tr>
			        		<th>IDr</th>
			        		<th>Who?</th>
			        		<th>Amount</th>
			            </tr>	
						{% for bid in bids  %}
			            <tr><td>{{bid.id}}</td>
			            	<td>{{bid.who }}</td>
			            	<td>{{bid.Amount}}</td>
			            </tr>
						{% endfor %}
						</table>
					      </div>
					    </div>
					  </div>
					</div>

				</div>


				<div class="col-lg-6">
									

					<div class="accordion" id="collapsibleTabs2">
					  <div class="card">
					    <div class="card-header" id="headingOne">
					      <h5 class="mb-0">
					        <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne2" aria-expanded="true" aria-controls="collapseOne">
					          Favorites
					        </button>
					      </h5>
					    </div>

					    <div id="collapseOne2" class="collapse show" aria-labelledby="headingOne" data-parent="#collapsibleTabs2">
					      <div class="card-body">
					        <table class="table table-striped table-bordered" border="1"> 
								        	<tr>
								        		<th>Item</th>
								        		<th>Type</th>
								        		<th>Link</th>
								            </tr>	
											{% for asset in assets  %}
								            <tr><td>{{asset.AID}}</td>
								            	<td>{{asset.Atype}}</td>
								            	<td>{{asset.WELL}}</td>
								            </tr>
											{% endfor %}
										</table>
					      </div>
					    </div>
  					</div>
					  <div class="card">
					    <div class="card-header" id="headingTwo">
					      <h5 class="mb-0">
					        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo2" aria-expanded="false" aria-controls="collapseTwo">
					         New Listings
					        </button>
					      </h5>
					    </div>
					    <div id="collapseTwo2" class="collapse" aria-labelledby="headingTwo" data-parent="#collapsibleTabs2">
					      <div class="card-body">
							<table class="table table-striped table-bordered" border="1"> 
			        	<tr>
			        		<th>IDr</th>
			        		<th>Who?</th>
			        		<th>Amount</th>
			            </tr>	
						{% for bid in listings  %}
			            <tr><td>{{bid.id}}</td>
			            	<td>{{bid.where}}</td>
			            	<td>{{bid.Amount}}</td>
			            </tr>
						{% endfor %}
					</table>
					      </div>
					    </div>
					  </div>
				  <div class="card">
				    <div class="card-header" id="headingThree">
				      <h5 class="mb-0">
				        <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree2" aria-expanded="false" aria-controls="collapseThree">
				          Saved Searches
				        </button>
				      </h5>
				    </div>
				    <div id="collapseThree2" class="collapse" aria-labelledby="headingThree" data-parent="#collapsibleTabs2">
				      <div class="card-body">
						<table class="table table-striped table-bordered" border="1"> 
			        	<tr>
			        		<th>IDr</th>
			        		<th>Who?</th>
			        		<th>Amount</th>
			            </tr>	
						{% for bid in bids  %}
			            <tr><td>{{bid.id}}</td>
			            	<td>{{bid.who }}</td>
			            	<td>{{bid.Amount}}</td>
			            </tr>
						{% endfor %}
						</table>
					      </div>
					    </div>
					  </div>
					</div>

				</div>
					



			</div>



<!--------------------------
            <div class="row">
				<div class="ed_frame col-lg-4">
					<h3>Current Holdings</h3>
					
			        <table class="table table-striped table-bordered" border="1"> 
			        	<tr>
			        		<th>Item</th>
			        		<th>Type</th>
			        		<th>Link</th>
			            </tr>	
						{% for asset in assets  %}
			            <tr><td>{{asset.AID}}</td>
			            	<td>{{asset.Atype}}</td>
			            	<td>{{asset.WELL}}</td>
			            </tr>
						{% endfor %}
					</table>

				</div>
				<div class="ed_frame col-lg-4">
					<h3>My Listings</h3>
					<table class="table table-striped table-bordered" border="1"> 
			        	<tr>
			        		<th>IDr</th>
			        		<th>Who?</th>
			        		<th>Amount</th>
			            </tr>	
						{% for bid in listings  %}
			            <tr><td>{{bid.id}}</td>
			            	<td>{{bid.where}}</td>
			            	<td>{{bid.Amount}}</td>
			            </tr>
						{% endfor %}
					</table>
				</div>
				<div class="ed_frame col-lg-4">
					<h3>Bids Received</h3>
						<table class="table table-striped table-bordered" border="1"> 
			        	<tr>
			        		<th>IDr</th>
			        		<th>Who?</th>
			        		<th>Amount</th>
			            </tr>	
						{% for bid in bids  %}
			            <tr><td>{{bid.id}}</td>
			            	<td>{{bid.who }}</td>
			            	<td>{{bid.Amount}}</td>
			            </tr>
						{% endfor %}
					</table>
				</div>
			</div>
		</div>







		<div class="container">
            <div class="row">
				<div class="ed_frame col-lg-4">
					<h3>Favorites</h3>
					<p>A table of favorites saved earlier. </p>
				</div>
				<div class="ed_frame col-lg-4">
					<h3>New Listings</h3>
					<p>A table of seller items posted on the site. </p>
				</div>
				<div class="ed_frame col-lg-4">
					<h3>Saved Searches</h3>
					<p>A table of searches as links to bring up pages </p>
				</div>
			</div>
		</div>
	-------------> 
</section>
{% endif %}
{% endblock %}

templates/royaltyDetails.html
{% extends 'base.html' %}

{% block content %}
<div class="row">
    <div class="col-lg-4"></div>
    <div class="col-lg-4">
        <h3>Assets available </h3>
        {{ object_list }}
        <table border="1"> 
        {% for well in allwells %}

            <tr><td>{{well.well_api}}</td><td>{{well.well_latt}}</td><td>{{well.well_long}}</td></tr>
        {% endfor %}
        </table>
    </div>
    <div class="col-lg-4"></div>
</div>
{% endblock %}

templates/signup.html
<!-- templates/registration/login.html -->
{% extends 'base.html' %}

{% block content %}

    <section class="bg-light">
        <div class="container">
            <div class="row">
                <div class="col-lg-2"></div>
                <div class="col-lg-8">
                <p>You are not logged in </p>
                <h2>Login</h2>
                <form method="post">
                  {% csrf_token %}
                  {{ form.as_p }}
                  <button type="submit">SIGN UP</button>
                </form>

                Or if you have an account then <a href="{% url 'login' %}">login</a>
                </div>
 
            <div class="col-lg-2"></div>
            </div>
        </div>
    </section>

{% endblock %}